// Generated by build.mjs. Upload this standalone file to GitHub.
const CLIENT = 'surfboard';
// Sub-Store 普通「文件」→ 文件操作 → 脚本操作。不是客户端内执行的 JS。
// 参数：#type=collection&name=你的组合订阅名称
// 或普通文件内容直接填入节点订阅/含节点的 Mihomo 配置，不传 name。
// 防止主函数报错后 Sub-Store 尝试快捷脚本模式而静默返回未生成的原文。
if (typeof $content !== 'undefined') throw new Error('配置生成失败，请查看前一条 operator 错误及后端日志');
async function operator(input, targetPlatform, context) {
  if (!input || typeof input.$content !== 'string') throw new Error('请在 Sub-Store 普通文件的文件操作中使用本脚本');
  const args = typeof $arguments === 'object' ? $arguments : {};
  const clone = x => JSON.parse(JSON.stringify(x));
  const unique = x => [...new Set(x)];
  const warn = msg => console.log(`[${CLIENT}] ${msg}`);
  let raw = args.name ? await produceArtifact({type: args.type || 'collection', name: args.name, platform: 'JSON', produceType: 'internal'}) : ProxyUtils.parse(input.$content);
  if (!Array.isArray(raw)) throw new Error('节点来源没有返回数组');
  const info = /官网|套餐|剩余(?:流量)?|流量剩余|到期|过期|订阅|客服|公告|Expire|Traffic|Subscription|Reset/i;
  const reserved = new Set(['DIRECT','REJECT','🚀 节点选择','🧭 手动选择','亚洲自动策略','全球自动策略','日本自动策略','新国自动策略','台湾自动策略','香港自动策略','美国自动策略','其他自动策略']);
  raw = clone(raw).filter(p => p && typeof p.name === 'string' && p.name.trim() && !info.test(p.name) && !['direct','reject','block','selector','urltest'].includes(p.type));
  // 不擅自改写节点链引用；发现复杂链时明确报错。
  if (raw.some(p => p['dialer-proxy'] || p['underlying-proxy'])) throw new Error('此版本不处理链式节点，请先在来源中移除链式节点');
  for (const p of raw) {
    const base = p.name.replace(/[\r\n,=]/g, ' ').trim();
    let name = base, n = 2;
    while (reserved.has(name)) name = `${base} (${n++})`;
    reserved.add(name); p.name = name;
  }
  if (!raw.length) throw new Error('没有有效节点，停止生成，避免空组直连');
  const regions = [
    ['日本自动策略',/(?:^|[^A-Za-z])(?:JP|JPN)\d*(?:$|[^A-Za-z])|日本|Japan|东京|東京|大阪|埼玉|🇯🇵/i],
    ['新国自动策略',/(?:^|[^A-Za-z])(?:SG|SGP)\d*(?:$|[^A-Za-z])|新加坡|Singapore|狮城|獅城|🇸🇬/i],
    ['台湾自动策略',/(?:^|[^A-Za-z])(?:TW|TWN)\d*(?:$|[^A-Za-z])|台湾|臺灣|Taiwan|🇹🇼/i],
    ['香港自动策略',/(?:^|[^A-Za-z])(?:HK|HKG)\d*(?:$|[^A-Za-z])|香港|Hong[\s_-]*Kong|🇭🇰/i],
    ['美国自动策略',/(?:^|[^A-Za-z])(?:US|USA)\d*(?:$|[^A-Za-z])|美国|美國|United[\s_-]*States|洛杉矶|洛杉磯|西雅图|西雅圖|🇺🇸/i],
    ['其他自动策略',/.*/]
  ];
  const groupsFor = names => regions.map(([name,re],i) => ({name, members:names.filter(n => regions.findIndex(([,r]) => r.test(n)) === i)})).filter(g => g.members.length);
  const main = '🚀 节点选择', manual = '🧭 手动选择', asia = '亚洲自动策略', global = '全球自动策略';
  const url = CLIENT === 'singbox' ? 'https://cp.cloudflare.com/generate_204' : 'http://cp.cloudflare.com/generate_204';
  const meta = 'https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo';
  const business = ['github','apple','onedrive','microsoft','openai','telegram','youtube','netflix','spotify','tiktok','google','steam'];
  const sets = [
    ['private','geosite','private','DIRECT'], ['geoip_private','geoip','private','DIRECT'],
    ['ads','geosite','category-ads-all','REJECT'],
    ['steam_cn','geosite','steam@cn','DIRECT'], ['games_cn','geosite','category-games@cn','DIRECT'],
    ...business.map(n => [n,'geosite',n,main]),
    ['cn','geosite','cn','DIRECT'], ['geoip_cn','geoip','cn','DIRECT'],
    ['geolocation_non_cn','geosite','geolocation-!cn',main]
  ];
  const directDomains = ['yuchsh.top'];
  const directExact = ['clash.razord.top','yacd.haishan.me'];
  const steamDomains = ['steamcontent.com','steamserver.net','steamchina.com'];
  const ruleURL = (kind,name,ext,base=meta) => `${base}/${kind}/${encodeURIComponent(name)}.${ext}`;
  // 构建顺序与 v9 相同：例外 → 私有 → 广告 → 国内游戏 → 业务 → 国内 → 海外兜底。
  const rulePlan = [
    ...directDomains.map(v => ({kind:'suffix',value:v,target:'DIRECT'})),
    ...directExact.map(v => ({kind:'domain',value:v,target:'DIRECT'})),
    ...sets.slice(0,3).map(s => ({set:s})),
    ...steamDomains.map(v => ({kind:'suffix',value:v,target:'DIRECT'})),
    ...sets.slice(3).map(s => ({set:s}))
  ];
  const encode = o => JSON.stringify(o,null,2);
  const yaml = o => ProxyUtils.yaml.safeDump(o,{lineWidth:-1});
  const demand = names => { if (!names.length) throw new Error('目标客户端没有支持的节点，停止生成'); };
  const hierarchy = names => {
    const rg = groupsFor(names);
    const an = rg.filter(g => regions.slice(0,4).some(([n]) => n === g.name)).map(g => g.name);
    const gn = [...(an.length ? [asia] : []), ...rg.filter(g => ['美国自动策略','其他自动策略'].includes(g.name)).map(g => g.name)];
    return {rg,an,gn};
  };
  // YAML domain/IP 规则转为通用条目；仅 Surfboard/Xray 使用，生成时固化规则。
  async function materialize() {
    const all = new Map();
    for (let start=0; start<sets.length; start+=4) {
      await Promise.all(sets.slice(start,start+4).map(async s => {
        const text = await ProxyUtils.download(ruleURL(s[1],s[2],'yaml'));
        const parsed = ProxyUtils.yaml.safeLoad(typeof text === 'string' ? text : text.body);
        if (!Array.isArray(parsed?.payload) || !parsed.payload.length) throw new Error(`规则集下载/解析失败: ${s[0]}`);
        all.set(s[0], parsed.payload.map(String));
      }));
    }
    return all;
  }
  function domainEntry(value) {
    if (value.startsWith('+.')) return {kind:'suffix',value:value.slice(2)};
    if (value.startsWith('*.')) return {kind:'wildcard',value:value.slice(2)};
    if (/[ *?]/.test(value)) throw new Error(`暂不支持规则通配符: ${value}`);
    return {kind:'domain',value};
  }
  const lines=ProxyUtils.produce(clone(raw),'Surfboard','internal');
  const names=lines.map(l=>l.slice(0,l.indexOf('=')).trim()); demand(names);
  const {rg,an,gn}=hierarchy(names);
  // 跨区 fallback 展平成节点列表，保留地区优先级和订阅顺序。
  const ordered=rg.flatMap(g=>g.members), asian=rg.filter(g=>an.includes(g.name)).flatMap(g=>g.members);
  const fallback=(n,m)=>`${n} = fallback, ${m.join(', ')}, url=${url}, interval=300, timeout=3`;
  const groups=[`${main} = select, ${[global,...(asian.length?[asia]:[]),...rg.map(g=>g.name),manual].join(', ')}`,
    `${manual} = select, ${[global,...names,'DIRECT'].join(', ')}`,fallback(global,ordered),
    ...(asian.length?[fallback(asia,asian)]:[]),...rg.map(g=>fallback(g.name,g.members))];
  const data=await materialize(), rules=[];
  function emit(e,t) {
    if(e.kind==='wildcard') throw new Error('规则包含仅子域通配符，无法无损转换 Surfboard: '+e.value);
    rules.push(`${e.kind==='suffix'?'DOMAIN-SUFFIX':'DOMAIN'},${e.value},${t}`);
  }
  for(const r of rulePlan) {
    if(!r.set) { emit(r,r.target); continue; }
    const [tag,kind,,target]=r.set;
    for(const v of data.get(tag)) {
      if(kind==='geoip') rules.push(`${v.includes(':')?'IP-CIDR6':'IP-CIDR'},${v},${target},no-resolve`);
      else emit(domainEntry(v),target);
    }
  }
  input.$content=['# Generated by Sub-Store; rules refresh when this file is regenerated.',
    '[General]','dns-server = 223.5.5.5, 119.29.29.29',`proxy-test-url = ${url}`,'test-timeout = 3','udp-policy-not-supported-behaviour = REJECT',
    '', '[Proxy]',...lines,'','[Proxy Group]',...groups,'','[Rule]',...unique(rules),`FINAL,${main}`,''].join('\n');
  return input;

}
