// Generated by build.mjs. Upload this standalone file to GitHub.
const CLIENT = 'xray';
// Sub-Store 普通「文件」→ 文件操作 → 脚本操作。不是客户端内执行的 JS。
// 参数：#type=collection&name=你的组合订阅名称
// 或普通文件内容直接填入节点订阅/含节点的 Mihomo 配置，不传 name。
// 防止主函数报错后 Sub-Store 尝试快捷脚本模式而静默返回未生成的原文。
if (typeof $content !== 'undefined') throw new Error('配置生成失败，请查看前一条 operator 错误及后端日志');
async function operator(input, targetPlatform, context) {
  if (!input || typeof input.$content !== 'string') throw new Error('请在 Sub-Store 普通文件的文件操作中使用本脚本');
  const args = typeof $arguments === 'object' ? $arguments : {};
  const clone = x => JSON.parse(JSON.stringify(x));
  const unique = x => [...new Set(x)];
  const warn = msg => console.log(`[${CLIENT}] ${msg}`);
  let raw = args.name ? await produceArtifact({type: args.type || 'collection', name: args.name, platform: 'JSON', produceType: 'internal'}) : ProxyUtils.parse(input.$content);
  if (!Array.isArray(raw)) throw new Error('节点来源没有返回数组');
  const info = /官网|套餐|剩余(?:流量)?|流量剩余|到期|过期|订阅|客服|公告|Expire|Traffic|Subscription|Reset/i;
  const reserved = new Set(['DIRECT','REJECT','🚀 节点选择','🧭 手动选择','亚洲自动策略','全球自动策略','日本自动策略','新国自动策略','台湾自动策略','香港自动策略','美国自动策略','其他自动策略']);
  raw = clone(raw).filter(p => p && typeof p.name === 'string' && p.name.trim() && !info.test(p.name) && !['direct','reject','block','selector','urltest'].includes(p.type));
  // 不擅自改写节点链引用；发现复杂链时明确报错。
  if (raw.some(p => p['dialer-proxy'] || p['underlying-proxy'])) throw new Error('此版本不处理链式节点，请先在来源中移除链式节点');
  for (const p of raw) {
    const base = p.name.replace(/[\r\n,=]/g, ' ').trim();
    let name = base, n = 2;
    while (reserved.has(name)) name = `${base} (${n++})`;
    reserved.add(name); p.name = name;
  }
  if (!raw.length) throw new Error('没有有效节点，停止生成，避免空组直连');
  const regions = [
    ['日本自动策略',/(?:^|[^A-Za-z])(?:JP|JPN)\d*(?:$|[^A-Za-z])|日本|Japan|东京|東京|大阪|埼玉|🇯🇵/i],
    ['新国自动策略',/(?:^|[^A-Za-z])(?:SG|SGP)\d*(?:$|[^A-Za-z])|新加坡|Singapore|狮城|獅城|🇸🇬/i],
    ['台湾自动策略',/(?:^|[^A-Za-z])(?:TW|TWN)\d*(?:$|[^A-Za-z])|台湾|臺灣|Taiwan|🇹🇼/i],
    ['香港自动策略',/(?:^|[^A-Za-z])(?:HK|HKG)\d*(?:$|[^A-Za-z])|香港|Hong[\s_-]*Kong|🇭🇰/i],
    ['美国自动策略',/(?:^|[^A-Za-z])(?:US|USA)\d*(?:$|[^A-Za-z])|美国|美國|United[\s_-]*States|洛杉矶|洛杉磯|西雅图|西雅圖|🇺🇸/i],
    ['其他自动策略',/.*/]
  ];
  const groupsFor = names => regions.map(([name,re],i) => ({name, members:names.filter(n => regions.findIndex(([,r]) => r.test(n)) === i)})).filter(g => g.members.length);
  const main = '🚀 节点选择', manual = '🧭 手动选择', asia = '亚洲自动策略', global = '全球自动策略';
  const url = CLIENT === 'singbox' ? 'https://cp.cloudflare.com/generate_204' : 'http://cp.cloudflare.com/generate_204';
  const meta = 'https://cdn.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@meta/geo';
  const business = ['github','apple','onedrive','microsoft','openai','telegram','youtube','netflix','spotify','tiktok','google','steam'];
  const sets = [
    ['private','geosite','private','DIRECT'], ['geoip_private','geoip','private','DIRECT'],
    ['ads','geosite','category-ads-all','REJECT'],
    ['steam_cn','geosite','steam@cn','DIRECT'], ['games_cn','geosite','category-games@cn','DIRECT'],
    ...business.map(n => [n,'geosite',n,main]),
    ['cn','geosite','cn','DIRECT'], ['geoip_cn','geoip','cn','DIRECT'],
    ['geolocation_non_cn','geosite','geolocation-!cn',main]
  ];
  const directDomains = ['yuchsh.top'];
  const directExact = ['clash.razord.top','yacd.haishan.me'];
  const steamDomains = ['steamcontent.com','steamserver.net','steamchina.com'];
  const ruleURL = (kind,name,ext,base=meta) => `${base}/${kind}/${encodeURIComponent(name)}.${ext}`;
  // 构建顺序与 v9 相同：例外 → 私有 → 广告 → 国内游戏 → 业务 → 国内 → 海外兜底。
  const rulePlan = [
    ...directDomains.map(v => ({kind:'suffix',value:v,target:'DIRECT'})),
    ...directExact.map(v => ({kind:'domain',value:v,target:'DIRECT'})),
    ...sets.slice(0,3).map(s => ({set:s})),
    ...steamDomains.map(v => ({kind:'suffix',value:v,target:'DIRECT'})),
    ...sets.slice(3).map(s => ({set:s}))
  ];
  const encode = o => JSON.stringify(o,null,2);
  const yaml = o => ProxyUtils.yaml.safeDump(o,{lineWidth:-1});
  const demand = names => { if (!names.length) throw new Error('目标客户端没有支持的节点，停止生成'); };
  const hierarchy = names => {
    const rg = groupsFor(names);
    const an = rg.filter(g => regions.slice(0,4).some(([n]) => n === g.name)).map(g => g.name);
    const gn = [...(an.length ? [asia] : []), ...rg.filter(g => ['美国自动策略','其他自动策略'].includes(g.name)).map(g => g.name)];
    return {rg,an,gn};
  };
  // YAML domain/IP 规则转为通用条目；仅 Surfboard/Xray 使用，生成时固化规则。
  async function materialize() {
    const all = new Map();
    for (let start=0; start<sets.length; start+=4) {
      await Promise.all(sets.slice(start,start+4).map(async s => {
        const text = await ProxyUtils.download(ruleURL(s[1],s[2],'yaml'));
        const parsed = ProxyUtils.yaml.safeLoad(typeof text === 'string' ? text : text.body);
        if (!Array.isArray(parsed?.payload) || !parsed.payload.length) throw new Error(`规则集下载/解析失败: ${s[0]}`);
        all.set(s[0], parsed.payload.map(String));
      }));
    }
    return all;
  }
  function domainEntry(value) {
    if (value.startsWith('+.')) return {kind:'suffix',value:value.slice(2)};
    if (value.startsWith('*.')) return {kind:'wildcard',value:value.slice(2)};
    if (/[ *?]/.test(value)) throw new Error(`暂不支持规则通配符: ${value}`);
    return {kind:'domain',value};
  }
  // 保守转换常用节点。复杂/未知协议明确跳过，不把它们伪装成兼容节点。
  function convert(p,i) {
    if(!['ss','vmess','vless','trojan','http','socks5'].includes(p.type)) throw new Error('未实现协议 '+p.type);
    if(p.plugin || p['shadow-tls'] || p['reality-opts'] && !['tcp','grpc',undefined].includes(p.network)) throw new Error('未实现插件或传输组合');
    if(p['tls-fingerprint'] || p['ca-str'] || p['client-cert'] || p['ech-opts']) throw new Error('未实现证书固定/自定义证书/ECH，避免丢失安全设置');
    const port=Number(p.port); if(!p.server || !Number.isInteger(port)||port<1||port>65535) throw new Error('地址/端口无效');
    const tag=`node-${String(i).padStart(4,'0')}-${p.name}`;
    const stream={network:p.network||'tcp',security:'none'};
    if(!['tcp','ws','grpc'].includes(stream.network)) throw new Error('未实现传输 '+stream.network);
    if(p.network==='ws') {
      const w=p['ws-opts']||{};
      if(w['max-early-data'] || w['v2ray-http-upgrade']) throw new Error('未实现 WS early-data/http-upgrade');
      stream.wsSettings={path:w.path||'/',headers:w.headers||{}};
    }
    if(p.network==='grpc') stream.grpcSettings={serviceName:p['grpc-opts']?.['grpc-service-name']||''};
    if(p['reality-opts']) {
      if(!p['reality-opts']['public-key']) throw new Error('REALITY 缺少公钥');
      stream.security='reality'; stream.realitySettings={serverName:p.sni||p.servername||p.server,fingerprint:p['client-fingerprint']||'chrome',publicKey:p['reality-opts']['public-key'],shortId:p['reality-opts']['short-id']||''};
    } else if(p.tls || p.type==='trojan') {
      stream.security='tls'; stream.tlsSettings={serverName:p.sni||p.servername||p.server,allowInsecure:p['skip-cert-verify']===true,fingerprint:p['client-fingerprint']||'chrome'};
      if(p.alpn) stream.tlsSettings.alpn=Array.isArray(p.alpn)?p.alpn:[p.alpn];
    }
    const server={address:p.server,port}; let settings,protocol=p.type;
    if(['vmess','vless'].includes(p.type)) {
      if(!p.uuid) throw new Error('缺少 UUID');
      if(p.type==='vmess' && Number(p.alterId||0)!==0) throw new Error('仅支持 AEAD VMess');
      const user={id:p.uuid};
      if(p.type==='vless') { user.encryption=p.encryption||'none'; if(p.flow) user.flow=p.flow; }
      else user.security=p.cipher||'auto';
      settings={vnext:[{...server,users:[user]}]};
    } else if(p.type==='ss') {
      protocol='shadowsocks';
      if(!['aes-128-gcm','aes-256-gcm','chacha20-ietf-poly1305','xchacha20-ietf-poly1305','2022-blake3-aes-128-gcm','2022-blake3-aes-256-gcm','2022-blake3-chacha20-poly1305'].includes(p.cipher)) throw new Error('不支持的 SS cipher');
      settings={servers:[{...server,method:p.cipher,password:p.password}]};
    } else if(p.type==='trojan') settings={servers:[{...server,password:p.password}]};
    else { protocol=p.type==='socks5'?'socks':'http'; settings={servers:[{...server,...(p.username?{users:[{user:p.username,pass:p.password||''}]}:{})}]}; }
    return {tag,protocol,settings,streamSettings:stream};
  }
  const out=[];
  raw.forEach((p,i)=>{try{out.push(convert(p,i));}catch(e){warn(`跳过 ${p.name}: ${e.message}`);}});
  demand(out.map(p=>p.tag));
  const data=await materialize();
  const rules=[];
  const target=t=>t==='DIRECT'?{outboundTag:'DIRECT'}:t==='REJECT'?{outboundTag:'REJECT'}:{balancerTag:'auto-leastLoad'};
  const domainValue=e=>e.kind==='suffix'?`domain:${e.value}`:e.kind==='wildcard'?`regexp:^.+\\.${e.value.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}$`:`full:${e.value}`;
  for(const r of rulePlan) {
    if(!r.set) { rules.push({type:'field',domain:[domainValue(r)],...target(r.target)}); continue; }
    const [tag,kind,,t]=r.set;
    const values=data.get(tag);
    rules.push({type:'field',[kind==='geoip'?'ip':'domain']:kind==='geoip'?values:values.map(v=>domainValue(domainEntry(v))),...target(t)});
  }
  rules.push({type:'field',network:'tcp,udp',balancerTag:'auto-leastLoad'});
  const expected=Number(args.expected||1);
  if(!Number.isInteger(expected)||expected<1) throw new Error('expected 必须是正整数');
  input.$content=encode({log:{loglevel:'warning'},
    inbounds:[{tag:'socks-in',listen:'127.0.0.1',port:10808,protocol:'socks',settings:{auth:'noauth',udp:true},sniffing:{enabled:true,destOverride:['http','tls'],routeOnly:true}},
      {tag:'http-in',listen:'127.0.0.1',port:10809,protocol:'http',settings:{}}],
    // 默认出站与 balancer 兜底均拒绝，避免观测未就绪/全部故障时直连。
    outbounds:[{tag:'REJECT',protocol:'blackhole',settings:{}},{tag:'DIRECT',protocol:'freedom',settings:{}},...out],
    routing:{domainStrategy:'IPIfNonMatch',rules,balancers:[{tag:'auto-leastLoad',selector:['node-'],fallbackTag:'REJECT',strategy:{type:'leastLoad',settings:{expected,maxRTT:'3s',tolerance:0.2}}}]},
    burstObservatory:{subjectSelector:['node-'],pingConfig:{destination:'https://cp.cloudflare.com/generate_204',interval:'1m',sampling:3,timeout:'3s'}}});
  return input;

}
